# Generated by Django 2.2.8 on 2020-01-08 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('Fn', 'Far-North'), ('N', 'North'), ('A', 'Adamawa'), ('L', 'Littoral'), ('C', 'Center'), ('W', 'West'), ('Nw', 'North-West'), ('Sw', 'South-West'), ('E', 'Eastern'), ('S', 'South')], default='Fn', max_length=2),
            preserve_default=False,
        ),
    ]
