# Generated by Django 2.2.8 on 2020-01-09 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_item_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('Av', 'Available'), ('N', 'Not-yet'), ('L', 'loading')], default='Av', max_length=2),
            preserve_default=False,
        ),
    ]
