# Generated by Django 2.2.8 on 2020-01-09 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200109_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='Gbomaman is the best food of Far North Region in Cameroon'),
            preserve_default=False,
        ),
    ]
