# Generated by Django 2.2.8 on 2020-01-13 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20200113_0159'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='additional_information',
            field=models.TextField(default='This is the test of additional description'),
            preserve_default=False,
        ),
    ]
