# Generated by Django 2.2.8 on 2020-01-13 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_item_additional_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='availabily',
            field=models.CharField(blank=True, choices=[('A', 'Available'), ('0', 'Ongoing'), ('H', 'Henceforth')], max_length=1, null=True),
        ),
    ]
